template_path: templates/crd.template

source_repositories:
  - url: https://github.com/appvia/terranetes-controller
    organization: appvia
    short_name: terranetes-controller
    commit_reference: develop
    crd_paths:
      - charts/terranetes-controller/crds
    cr_paths:
      - docs/crds
    metadata:
      contexts.terraform.appvia.io:
        owner:
          - https://github.com/orgs/appvia/teams/product
        topics:
          - terraform
      cloudresources.terraform.appvia.io:
        owner:
          - https://github.com/orgs/appvia/teams/product
        topics:
          - terraform
      configurations.terraform.appvia.io:
        owner:
          - https://github.com/orgs/appvia/teams/product
        topics:
          - terraform
      plans.terraform.appvia.io:
        owner:
          - https://github.com/orgs/appvia/teams/product
        topics:
          - terraform
      policies.terraform.appvia.io:
        owner:
          - https://github.com/orgs/appvia/teams/product
        topics:
          - terraform
      providers.terraform.appvia.io:
        owner:
          - https://github.com/orgs/appvia/teams/product
        topics:
          - terraform
      revisions.terraform.appvia.io:
        owner:
          - https://github.com/orgs/appvia/teams/product
        topics:
          - terraform
