name: Test deployment

on:
  pull_request:
    branches:
      - master

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: NPM Build
        run: |
          export DOCUSAURUS_IGNORE_SSG_WARNINGS=true
          npm ci
          npm run build
